[32mINFO    [0m root:test_004_advanced_features.py:195 **** Starting test_broken_links ****
[31m[1mERROR   [0m root:test_004_advanced_features.py:212 Error checking link https://the-internet.herokuapp.com/img/forkme_right_green_007200.png: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /img/forkme_right_green_007200.png (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)')))
[31m[1mERROR   [0m root:test_004_advanced_features.py:212 Error checking link https://the-internet.herokuapp.com/asdf.jpg: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /asdf.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)')))
[31m[1mERROR   [0m root:test_004_advanced_features.py:212 Error checking link https://the-internet.herokuapp.com/hjkl.jpg: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /hjkl.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)')))
[31m[1mERROR   [0m root:test_004_advanced_features.py:212 Error checking link https://the-internet.herokuapp.com/img/avatar-blank.jpg: HTTPSConnectionPool(host='the-internet.herokuapp.com', port=443): Max retries exceeded with url: /img/avatar-blank.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)')))
[32mINFO    [0m root:test_004_advanced_features.py:216 **** test_broken_links COMPLETED ****