{"uuid": "fe247a65-df9e-4da2-abb2-2a410cf9f38e", "children": ["4cd83f2a-e6d1-447c-bd2d-a317a3025e09"], "befores": [{"name": "class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: MicrosoftEdge=141.0.3537.85)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff75fb72a75+51877]\n\tGetHandleVerifier [0x0x7ff75fb72ad4+51972]\n\tGetHandleVerifier [0x0x7ff75fd29425+1848405]\n\t(No symbol) [0x0x7ff75f8c0e5f]\n\t(No symbol) [0x0x7ff75f9574ec]\n\t(No symbol) [0x0x7ff75f96ed0a]\n\t(No symbol) [0x0x7ff75f951df3]\n\t(No symbol) [0x0x7ff75f925b36]\n\t(No symbol) [0x0x7ff75f924d80]\n\t(No symbol) [0x0x7ff75f925973]\n\t(No symbol) [0x0x7ff75f9ee4a5]\n\t(No symbol) [0x0x7ff75f9ea75d]\n\tGetHandleVerifier [0x0x7ff75fb9d2b3+226019]\n\tGetHandleVerifier [0x0x7ff75fb8c481+156849]\n\tGetHandleVerifier [0x0x7ff75fb94979+190889]\n\tGetHandleVerifier [0x0x7ff75fb79bb4+80868]\n\tGetHandleVerifier [0x0x7ff75fb79d03+81203]\n\tGetHandleVerifier [0x0x7ff75fb68286+8886]\n\tBaseThreadInitThunk [0x0x7ffa3871e8d7+23]\n\tRtlUserThreadStart [0x0x7ffa3950c53c+44]\n\n", "trace": "  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\Capstone_Selenium_Pytest\\testCases\\test_002_inventory_and_cart.py\", line 20, in class_setup\n    self.driver.get(self.baseURL)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 483, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1761071887712, "stop": 1761071887714}], "start": 1761071887712, "stop": 1761071887794}