{"uuid": "44646cd3-637c-4b27-9332-c0f40545e9a1", "children": ["c67504a1-05a4-40ba-9106-f24140487a4b", "cfd0a88c-adfd-4a49-bc1a-52dd19a6e606", "d089d1f8-e416-4c46-a4e5-e399bfcb60a6", "db059791-24e7-4ff0-af9a-5ab1c34eb4ea", "b196feb7-6a05-4ed9-9804-b35603e9f32a", "65ce72b8-6088-48a1-aa6e-f1c12b6097f7", "d963e536-5d3a-4d99-8854-c54eab86f93b", "691c9db9-c85a-4037-933e-3b647190e860", "34485350-53ff-4edb-acce-ba059d830148"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "trace": "  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\Capstone_Selenium_Pytest\\testCases\\conftest.py\", line 45, in setup\n    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()), options=firefox_options)\n                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 107, in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n        url=self.latest_release_url,\n        headers=self.auth_header\n    )\n  File \"C:\\Users\\Ascendion\\CapstoneProject\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 35, in get\n    raise exceptions.ConnectionError(f\"Could not reach host. Are you offline?\")\n"}, "start": 1761071965285, "stop": 1761071966943}], "start": 1761071965285, "stop": 1761071968227}