[32mINFO    [0m root:test_001_login.py:83 **** Starting test_login_data_driven for problem_user ****
[32mINFO    [0m root:test_001_login.py:93 Expecting PASS
[32mINFO    [0m root:test_001_login.py:98 **** Test PASSED for problem_user (Expected: Pass) ****